### ISSUE TITLE
Should locality.type also have an enumeration?

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/vip-specification#129]
I imagine there are a finite number of values here, but should we limit the possibilities rather than use `xs:string`? Probably not crucial for 5.0, but thought I'd put this up for discussion.

**Comment by jdmgoogle** [comment]
What are everyone's thoughts on using the `DistrictType` enumeration here?

**Comment by cjerdonek** [comment]
If I understand locality correctly, I don't think `DistrictType` should be used for the simple reason that it contains values that would be invalid as a locality type.  (DistrictType even has "locality" as an option.)  Also, it's usually best not to have something try to serve two purposes.

Depending on the meaning of ElectoralDistrict versus Locality,  _maybe_ (and it's a weak maybe) it would make sense to have DistrictType extend a locality type.  But again, that would lock in a relationship that we might not want to hold true going forward.  My instinct is that they should be unrelated.

For discussion purposes, it seems like the possible known values should be listed.

**Comment by jungshadow** [comment]
@cjerdonek Potential values for locality are determined by what jurisdiction is the election administrator (e.g. town, county, municipality, city, parish, et al) and contains the associated precincts.

@nomadaisy Might have a better idea on a more exhaustive list.

**Comment by jktomer** [comment]
What's the purpose of locality.type? It exists in the 3.0 feed, and we read but do not use it.

**Comment by jungshadow** [comment]
@jktomer For those jurisdictions using the specification to share data between systems or external services, segmenting the locality data into its disparate pieces is as useful as separating candidate names or standardizing addresses. I imagine there are other uses, but that's the first that comes to mind.

**Comment by jdmgoogle** [comment]
@jungshadow Do you know of any jurisdictions which are (a) currently using or planning to use the data in this way, and (b) using the `locality.type` field as part of the reconciliation process?

**Comment by jungshadow** [comment]
@jdmgoogle (a) A handful that are currently using it. Some for ballot generation (it may not matter here) and a few to prime online overseas voter services (knowing the local election authority figures in here). (b) Good question. I don't, but I can see how it would be useful to have the type separate from the name for categorical purposes.

I'm honestly not sure if narrowing the scope of types would help folks in this area, but there are three needs I'm looking at here: ours (coming up with a common set of terms for elections), Google's (the API), and jurisdictions (communication between systems/services).

**Comment by jdmgoogle** [comment]
Okay. @johnpwack posted this in response to my request for clarification about the different types

> City – keep this, would be used for cities that report votes, e.g., Chicago
Jurisdiction – to me it doesn't seem any more useful than using "Other" – I suggest removing it
Local – I believe this is intended to be used for a local district, but again it doesn't seem any more useful than using "Other" and I suggest removing it
Locality – this was probably added so as to be compatible with VIP but again I suggest removing it if this is not needed for compatibility
Municipality – keep this, it is used as a more general term for villages and townships, at least in Wisconsin

Thoughts?

**Comment by jungshadow** [comment]
@jdmgoogle Narrowing the number of types sounds good to me, but is this going back to the idea of reusing DistrictType?

**Comment by jdmgoogle** [comment]
@jungshadow Yes. I don't see the benefit in creating a second set of almost-entirely-overlapping enums when the first set appears to meet our needs.

**Comment by pkoms** [comment]
Quick note on why locality.type is useful: there are states where townships run elections, but townships in different counties have the same name. (Michigan, Wisconsin come to mind.) So to truly tell these towns apart without reference to third-party information, we'd need to be able to identify what county they're in, for which we'd want both county and municipal locality objects. *But,* counties also share names with townships, so the entire thing would become an indistinguishable mess without a helping hand from locality.type.

I don't see why city and municipality need to be separate items here. From the perspective of election administration, a city is just a really big municipality. Wisconsin has villages, townships, and cities, and they're all bundled together under municipality.

**Comment by jdmgoogle** [comment]
@pkoms In order to differentiate between two towns with identical names in different counties we'd need a hierarchy of `Locality` objects, which is orthogonal to the `Type` element we're discussing here (I believe). The `Locality` object does contain an `ExternalIdentifiers` element, which is where an OCD-ID should go, which would allow us to differentiate between the two identically-named towns.

Does this (the external ID support) address your concern, or is there some other use of `Locality.Type` to which you're referring that I'm missing?

As for the city/municipality thing, I'll leave that to the larger group to discuss.

**Comment by pkoms** [comment]
Thanks for the reminder about `ExternalIdentifiers`. I'll take it.

**Comment by jktomer** [comment]
Just to chime in, since Google still has no plans to use =locality.type= for anything, we have only an academic interest in how it's defined.

But I'll echo @jdmgoogle's comment that the right way to unambiguously identify a locality is with OCD division IDs, and caution you against trying to reinvent them in some other format, because it was kind of difficult to do the first time :)

(Seriously, the mention of township name collisions gave me flashbacks... did you know there are _eight_ Liberty, PA's? And that this was allowed to happen _even though townships are incorporated at the state level_?)

**Comment by jktomer** [comment]
> I don't see why city and municipality need to be separate items here. From the perspective of election administration, a city is just a really big municipality. Wisconsin has villages, townships, and cities, and they're all bundled together under municipality.

To be perfectly honest, city, locality, and municipality all sound like synonyms (or regional spelling variations of synonyms) to me; I don't know of any case where having more than one of those three could resolve an ambiguity of any kind.

**Comment by jungshadow** [comment]
Solid. Generally, are we agreed that we can just re-purpose DistrictType? The locality either falls into one of the given types or it's an "other."

**Comment by jdmgoogle** [comment]
LGTM. I'll make a PR.

**Comment by kennethmbennett** [comment]
Technically speaking, municipality is more of a legal term, which refers to a city or town that has a legal corporate status and its own local government.  The term city in the general sense refers to any large human settlement, whether legally incorporated or not.   We often use the words municipality and city interchangeably because (in the “developed” world at least) most large human settlements we would call cities are also legally incorporated.

Not sure this fun fact for the day helps out with the spec, but hopefully it sheds some light on terms we are dealing with.
