### ISSUE TITLE
Fix PollingLocation Documentation Issues

### ISSUE THREAD

**Issue by pkoms** [votinginfoproject/vip-specification#220]
Reconcile these two cells in https://github.com/votinginfoproject/vip-specification/blob/vip5/docs/xml/elements/polling_location.rst

Required? | Error Handling?
-------------- | -------------
Optional | If the field is invalid or not present, the implementation is required to ignore the PollingLocation element that contains it.

**Comment by jungshadow** [comment]
I'm expanding the scope of the issue a bit since there are a few other issues that are mostly cosmetic and really don't need separate issues:

- [ ] Fix mismatch between **Error Handling** and **Required?** columns as listed above
- [ ] Link to `HoursOpen` doc in `PollingLocation.Hours` description
- [ ] Add `LatLng` header before its preamble and table and fix `PollingLocation.LatLng` link (**NB:** this is so the `LatLng` shows up in the sidebar as a sublink like many of the other elements).
