### ISSUE TITLE
xsd:ID documentation should be more explicit about rules

### ISSUE THREAD

**Issue by indymag** [votinginfoproject/vip-specification#366]
The current documentation makes xsd:ID hungarian notation sound optional.  The documentation should be updated to be clear that there are some requirements that MUST be adhered to as part of the expectations for xsd:ID.  It should also link to something authoritative and also hopefully accessible.

I found the following from http://www.datypic.com/sc/xsd/t-xsd_ID.html but there is probably something better.
---------------------------
The type xsd:ID is used for an attribute that uniquely identifies an element in an XML document. An xsd:ID value must be an NCName. This means that it must start with a letter or underscore, and can only contain letters, digits, underscores, hyphens, and periods.

xsd:ID carries several additional constraints:

Their values must be unique within an XML instance, regardless of the attribute's name or its element name.
A complex type cannot include more than one attribute of type xsd:ID, or any type derived from xsd:ID.
xsd:ID attributes cannot have default or fixed values specified.

**Comment by jdmgoogle** [comment]
Ah, this seems to be a conflation of two things. The first is the requirement to adhere to the `xs:ID` specification, and the second is to use Hungarian notation to describe the type of object being defined/referenced. The first is required, but the second is optional. A state could produce a feed with object IDs like

state00
county001
city002
cityCouncilSeat001atLarge

and be good according to the former but not the latter. Some states pushed back on the idea of Hungarian notation being required because they had their own naming schema, and honestly there wasn't a way to enforce it.

They should, however, be producing valid XML, and if their `xs:ID` elements don't start with a letter or underscore they should get a schema error when they try to validate it.

We can update the documentation to link to the `xs:ID` definition, and indicate (again) that they need to produce valid XML. :)
