### ISSUE TITLE
Changelog missing from web documentation

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#40]
The web documentation has a link to a "Changelog" in the left column under "Revision History," but there is no Changelog section.

**Comment by jungshadow** [comment]
Hi, @cjerdonek. On a general note, it's great to have you digging in here. As for the issue at hand, since we've been on GitHub, we've retired the changelog for the issues and pull-request discussions as they tend to be substantially more meaningful. Apparently, we forgot to remove all of its remnants. We'll update the current documentation.

@nomadaisy Would you mind taking this one on, since you're currently working on some doc changes?

**Comment by cjerdonek** [comment]
Hi @jungshadow, thanks, and you're welcome.  I do have a couple higher-level thoughts / questions about the organization of the various versions, but I'll hold off on mentioning those until I gain a little more familiarity with the project.

Regarding this issue, as an interested observer, I do think that a simple list of the changes from one version to the next would go a long way towards helping observers know how the versions differ from one another (e.g. attribute `foo` added, attribute `bar` removed or renamed, etc).  As it stands now, I couldn't find an easy way to uncover that information.  FWIW, on other projects I've been involved with, the changelog entries have links to the individual issue pages (when they exist), so that people can easily track down the context and discussion around the various changes.

**Comment by jungshadow** [comment]
Feel free to reach out to us at info@votinginfoproject.org and set up a time to chat if you feel like it might be easier to discuss things over the phone :)

Hmm...I can understand the utility of the changelog. Personally, I'm not a fan of them because of the additional burden it puts on the team to re-digest and regurgitate–to use a rather unpleasant verb–a lot of the tracking that's already been done by the systems we use (e.g. GitHub, Basecamp [for general inter-team communication], et al). That said, I'd rather have the group decide if they want to keep one and it's conceivably easier to create one now that we mandate the use of milestones, issues, and pull-requests.

@pstenbjorn, @pkoms, @nomadaisy, @jdmgoogle: Being some of the more active folks on here, how do you feel about keeping a changelog?

**Comment by pstenbjorn** [comment]
@jungshadow I am general agreement that for a schema a changelog is a bit of a burden, however, I think ensuring that pull requests and other commits have reasonably complete comments regarding the nature of the commits it would server a similar purpose.

**Comment by cjerdonek** [comment]
I'll make one more comment on this and then stay quiet for a bit. :grinning: One of the use cases for a list of changes to the spec is for implementers and consumers to get a sense of what the breaking changes and enhancements are from one version of the spec to the next (for things like level of effort, incompatibilities, etc).

It seems like it would be hard and a lot messier to have to manually glean this information from the [commit history](https://github.com/votinginfoproject/vip-specification/commits/master).  A changelog also has the advantages of (1) the ability to be edited after the fact (to fix typos, simplify the organization, etc), and (2) being more portable (e.g. can be easily included in and read from the web site itself).

**Comment by pkoms** [comment]
I'm of two minds here. I also don't want to go through documenting this work bit by bit. On the other hand, the pull requests and their comments can get very granular, and having somewhere I can go for a higher-level survey of the work that's been done would be valuable. I think I lean slightly towards keeping a changelog, at least once we hit 5.0.

Since many of these changes are already described in Google's list of desired spec enhancements, we should be able to take that as a jumping-off point for the first changelog entry.

**Comment by jungshadow** [comment]
@cjerdonek I agree that all of the older updates make it nearly impossible to find out what's changed from release-to-release and the why. This is largely why we deliberately regiment the way we commit, make pull requests, and always have a related issue. To me, I'd prefer to look at everything in the "Version 5.0" Milestone bucket and see why a particular change was made rather than trying to digest a text file. But, again...not entirely up to me :)

Currently, it seems we have:
* For: @cjerdonek 
* Against: @pstenbjorn @jungshadow
* Undecided: @pkoms ;)

**Comment by jdmgoogle** [comment]
What was the verdict on this? ISTR some discussion about this topic happening on other threads but I don't recall the final decision (if there was one).

**Comment by cjerdonek** [comment]
There will be release notes for v5.0 onwards.  The section hasn't been stubbed out yet though.

**Comment by cjerdonek** [comment]
I made PR #95 to stub out release notes.  This gives people a place to write things.  I only put two issues that I had involvement in, but other people can add more.

**Comment by jdmgoogle** [comment]
To clarify, @cjerdonek is referring to this link:

http://votinginfoproject.github.io/vip-specification/#changelog

**Comment by jungshadow** [comment]
I just realized that I skirted the formal process on this one. Mah bad, but this is fixed: http://votinginfoproject.github.io/vip-specification/

**Comment by cjerdonek** [comment]
Per yesterday's discussion, wasn't part of this issue to add to the _new_ documentation a link to the release notes?

**Comment by jungshadow** [comment]
Ah...yes it was. Forgot about that.
