### ISSUE TITLE
Prefix xs:ID typed elements in VIP 6.0 Sample File

### ISSUE THREAD

**Issue by JDziurlaj** [votinginfoproject/vip-specification#430]
Sample file `vipfeed-04013-2020-11-03.xml` in `sample_feed_v6.zip` contains two invalid values for `xs:ID` typed elements (`id`s, lines 2, 10).

```xml
<VipObject schemaVersion="6.0">
	<Source id="4013555">
		<Name>MARICOPA COUNTY BOARD OF ELECTIONS</Name>
		<VipId>04013</VipId>
		<DateTime>2020-08-04T00:00:00</DateTime>
	</Source>
	<State id="st04">
		<Name>ARIZONA</Name>
	</State>
	<Election id="401311032020">...</Election>
	...
</VipObject>
```

**Comment by jswiesner** [comment]
I think there are two issues here:

1. The sample feed has IDs that violate the NCName convention since they begin with a number.
2. Broader question about whether the VIP spec should start such IDs. I understand there is some precedent of VIP feeds allowing IDs that begin with a number, so we will need to take this into account.

@afsmythe WDYT about updating the sample feed to include a prefix to address (1) so that at least the sample feed complies with the NCName convention, and then opening a separate issue to start a broader discussion about (2) to inform possible future changes to the spec?

**Comment by afsmythe** [comment]
Fixed in this PR https://github.com/votinginfoproject/vip-specification/pull/435

**Comment by afsmythe** [comment]
Closing.
