### ISSUE TITLE
Consider xs:anyUri type for ExternalFile/FileName

### ISSUE THREAD

**Issue by JDziurlaj** [votinginfoproject/vip-specification#432]
Consider the use of `xs:anyUri` so that other URI schemes could be used (e.g. http, ftp, etc.) to resolve external resources.

**Comment by jswiesner** [comment]
This would be useful to have future flexibility for externally hosted resources. What would a value of ExternalFile/FileName look like for external files embedded within the feed archive (alongside the XML file)? Would it need to include a file:// protocol (e.g. "file://shapefile.zip")?

**Comment by JDziurlaj** [comment]
I don't believe you'd need to use the `file` scheme here unless you wanted to be extra explicit. See [here](https://docstore.mik.ua/orelly/xml/xmlnut/ch21_03.htm).

**Comment by jswiesner** [comment]
That sounds good. I also think this makes sense since there's a strong precedent in the spec for using xs:anyUri to reference external resources.

WDYT about renaming FileName to FileUri and changing the type from xs:string to xs:anyUri? @afsmythe thoughts? If everyone agrees then we could make this change as part of 6.0.

**Comment by afsmythe** [comment]
SGTM!

**Comment by afsmythe** [comment]
PR created https://github.com/votinginfoproject/vip-specification/pull/433

**Comment by afsmythe** [comment]
Closing..
