### ISSUE TITLE
Create separate CSV documentation

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/vip-specification#60]
Does the CSV format deserve its own documentation or should it be integrated with the XML spec documentation? I can see a lot of overlap, so it may make sense to keep them integrated, but the new spec may also make the resultant CSVs an animal in and of themselves.

**Comment by cjerdonek** [comment]
Personally, I think the CSV format could use its own page, even if the page starts out only as an overview with high-level guidance.

Given that `index.html` is quite large, one thing I was wondering about if there is some way it can be broken up and made DRY and easier to maintain.  For example, it could be made into a template with the chunks for each object type plugged in (a bit like the CSV and XML data sources, an approach I really like by the way).  Moving in this direction would open up the possibility for having different "views" of the spec (e.g. CSV and XML views), so that the same information wouldn't need to be maintained in two different places.

But for starters, I think a "CSV Overview" page would be good and easier to do.

**Comment by jdmgoogle** [comment]
Temporarily assigning @nomadaisy to this as she seems to be most familiar with the CSV format.

Noma: feel free to assign this to someone else if either someone else would be more knowledgeable about it or you're currently overloaded.

**Comment by jungshadow** [comment]
@nomadaisy Let me know if you want to talk through the documentation structure. If you need a Sphinx/rst primer, I can help there as well.

**Comment by nomadaisy** [comment]
@jungshadow That would be great. Let's schedule something.

**Comment by afsmythe** [comment]
This can be closed. There was already separate CSV documentation, and with PR https://github.com/votinginfoproject/vip-specification/pull/376 the CSV spec has been codified within the YAML files.
